### ISSUE TITLE
Check colormap failures

### ISSUE THREAD

**Issue by cliffckerr** [sciris/sciris#161]
Not compatible with Matplotlib 3.4.0:
```
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sciris
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/software/anaconda3/envs/tmp_mpl/lib/python3.8/site-packages/sciris/__init__.py", line 16, in <module>
    from .sc_plotting  import *
  File "/software/anaconda3/envs/tmp_mpl/lib/python3.8/site-packages/sciris/sc_plotting.py", line 745, in <module>
    pl.cm.register_cmap('turbo',      turbocolormap())
  File "/software/anaconda3/envs/tmp_mpl/lib/python3.8/site-packages/matplotlib/cm.py", line 149, in register_cmap
    raise ValueError(msg)
ValueError: Trying to re-register the builtin cmap 'turbo'.
```

```
/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/sciris-1.0.0-py3.8.egg/sciris/sc_plotting.py:745: in <module>
    pl.cm.register_cmap('turbo',      turbocolormap())
/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/matplotlib-3.4.0rc1-py3.8-linux-x86_64.egg/matplotlib/cm.py:149: in register_cmap
    raise ValueError(msg)
E   ValueError: Trying to re-register the builtin cmap 'turbo'.
```

**Comment by cliffckerr** [comment]
Done
