### ISSUE TITLE
Can't delete by index in sc.odict()

### ISSUE THREAD

**Issue by cliffckerr** [sciris/sciris#376]
```py
In[6]: import sciris as sc
In[7]: x = sc.odict(foo=1,bar=2)
In[8]: x
Out[8]: #0: 'foo': 1
#1: 'bar': 2

In[9]: del x[0]
Traceback (most recent call last):
  File "C:\Users\romesh\miniconda3\envs\atomica38\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-ec9e6e663ef5>", line 1, in <module>
    del x[0]
  File "C:\Users\romesh\projects\sciris\sciris\sc_odict.py", line 364, in __delitem__
    return OD.__delitem__(self, *args, **kwargs)
KeyError: 0
```

**Comment by cliffckerr** [comment]
Done
