### ISSUE TITLE
R2: Fix helloworld app

### ISSUE THREAD

**Issue by cliffckerr** [sciris/sciris#438]
The helloworld webapp does not run
```
(clean) ~/s/p/s/s/e/helloworld develop|✓
✔ 17:38:46 $ python app.py
Traceback (most recent call last):
  File "/home/tcaswell/source/p/sciris/scirisweb/examples/helloworld/app.py", line 16, in <module>
    import scirisweb as sw
  File "/home/tcaswell/source/p/sciris/scirisweb/scirisweb/__init__.py", line 17, in <module>
    from .sw_app       import * # analysis:ignore
  File "/home/tcaswell/source/p/sciris/scirisweb/scirisweb/sw_app.py", line 27, in <module>
    from werkzeug.serving import run_with_reloader
ImportError: cannot import name 'run_with_reloader' from 'werkzeug.serving' (/tmp/clean/lib/python3.10/site-packages/werkzeug/serving.py)
```
I get this error both with scirisweb installed from pip and from the develop branch of scirisweb (following instructions from https://github.com/sciris/sciris#20-second-quick-start-guide-for-scirisweb). I guess this is out of scope for the paper, but reading through the README it was one of the first things I tried.

**Comment by cliffckerr** [comment]
cc https://github.com/openjournals/joss-reviews/issues/5076

**Comment by cliffckerr** [comment]
This should definitely be fixed :) For now, though, I've tried to decouple Sciris and ScirisWeb; the readme for the former no longer discusses ScirisWeb, and in the JOSS paper it's only mentioned briefly at the end.
