### ISSUE TITLE
Fix conda installation

### ISSUE THREAD

**Issue by cliffckerr** [sciris/sciris#491]
Due to a Matplotlib version incompatibility:
```py
>>> import sciris as sc                                                                                               
Traceback (most recent call last):                                                                                    
  File "<stdin>", line 1, in <module>                                                                                 
  File "/software/anaconda3/envs/scc/lib/python3.9/site-packages/sciris/__init__.py", line 39, in <module>            
    from .sc_colors     import *                                                                                      
  File "/software/anaconda3/envs/scc/lib/python3.9/site-packages/sciris/sc_colors.py", line 18, in <module>           
    from matplotlib import colors as mplc, colormaps as mplcm                                                         
ImportError: cannot import name 'colormaps' from 'matplotlib' (/software/anaconda3/envs/scc/lib/python3.9/site-packages/matplotlib/__init__.py)   
```

**Comment by cliffckerr** [comment]
Done
